# -*- coding: utf-8 -*-
"""ArbolnobinarioBigtree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9J8TDvO_Xfv15u2rzyg1RxulkuY0Jjm
"""

pip install bigtree

from bigtree import list_to_tree

path_list = [] #we left the list empy so the user can create the tree as they visualize it
root = None

def agregar_nodo():
    print("\nIngrese la ruta del nodo (ej: A/B/C): ")
    ruta = input("Ruta: ")

    if ruta.strip() == "":
        print("Ruta inválida")
        return

    path_list.append(ruta)
    print("Nodo agregado")


def mostrar_arbol():
    if not path_list:
        print("Árbol vacío")
        return

    root = list_to_tree(path_list)
    print("\nÁrbol:\n")
    root.show()


# MENÚ
while True:
    print("\nMENU")
    print("1. Agregar nodo")
    print("2. Mostrar árbol")
    print("3. Salir")

    op = int(input("Opción: "))
    match op:
      case 1:
        agregar_nodo()

      case 2:
        mostrar_arbol()

      case 3:
        print("Saliendo...")
        break

      case _:
        print("Opción inválida")